import type { Metadata } from 'next'
import { ConvexClientProvider } from './ConvexClientProvider'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  Show,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'
import { Button } from '@/components/ui/button'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col overflow-hidden`}>
        <ClerkProvider dynamic>
          <header className="sticky top-0 z-50 flex justify-between items-center p-4 gap-4 h-16 shrink-0 border-b bg-background">
            <div className="flex justify-end items-center gap-4">
              <Show when="signed-out">
                <SignInButton />
                <SignUpButton>
                  <Button>
                    Sign Up
                  </Button>
                </SignUpButton>
              </Show>
              <Show when="signed-in">
                <UserButton />
              </Show>
            </div>
          </header>
          <ConvexClientProvider>
            <main className="flex-1 overflow-auto">
              {children}
            </main>
          </ConvexClientProvider>
          <Toaster richColors position="top-right" />
        </ClerkProvider>
      </body>
    </html>
  )
}